"""Color palette and style constants for the application UI."""

# Color palette
BG_MAIN = "#eeebe2"
NEUTRAL_TEXT = "#8e8985"
GREEN_MEDIUM = "#395b5c"
GREEN_VARIANT = "#385a5b"
GREEN_DARK = "#1c5a59"
BLUE_INSTITUTIONAL = "#104064"
BLUE_PRIMARY = "#003e63"
BLUE_DARKER = "#19374f"

# UI mappings
HEADER_BG = BLUE_PRIMARY
HEADER_FG = "#ffffff"
BTN_PRIMARY_BG = BLUE_PRIMARY
BTN_PRIMARY_FG = "#ffffff"
BTN_SECONDARY_BG = GREEN_MEDIUM
BTN_SECONDARY_FG = "#ffffff"
HOVER_COLOR = GREEN_DARK
INPUT_BG = "#ffffff"
INPUT_BORDER = NEUTRAL_TEXT
ERROR_BORDER = "#cc0000"
STATUS_OK = GREEN_DARK
STATUS_WARN = "#b87c00"
SECTION_TITLE = BLUE_DARKER
BODY_TEXT = BLUE_PRIMARY

# Font preferences
FONT_FAMILY = "Segoe UI"
FONT_SIZE_NORMAL = 12
FONT_SIZE_SMALL = 10
FONT_SIZE_TITLE = 14
FONT_SIZE_HEADER = 18
